name: ci
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: >
          sudo apt-get install -y
          ninja-build
      - run: >
          cmake
          -S .
          -B build
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
      - run: cmake --build build --verbose
      - run: ./build/fft ./440Hz.wav 0 4096 ./A.csv
      - run: cat ./A.csv
